# Main menu buttons
main_menu_buttontxt = ["📖 Qur'oni Karim", "☀️ Siyrat", "🌕 Ramazon", "📚 Ilmiy suhbatlar",
                       "☪️ Tahorat, namoz va zikrlar", "❓ Savol yuborish"]

# Quranapds - Quran audio photo documents
quranapdsdict = {
    "Qur'oni Karim tilovati (Hasanxon va Husaynxon qorilar)": "recitationmuqriy",
    "Qur'on bilan tanishuv": "qurantanishuv",
    "Mus'har istilohlari sharhi": "quranistiloh",
    "Iqro": "quraniqro",
    "O'n kecha bilan qasam (1-bosqich)": "onkechabir",
    "O'n kecha bilan qasam (2-bosqich)": "onkechaikki",
    "O'n kecha bilan qasam (3-bosqich)": "onkechauch",
    "Qur'on tartili": "qurantartil",
    "Qur'oni Karim tilovati (ta'lim uslubida)": "husarymuallim",
    "Qur'oni Karim (rasm/matn)": "quranrasm/matn",
    "Qur'on ta'limiga oid suhbat va tavsiyalar": "quransuhbattavsiya",
    "Qur'on ila hamnafas": "quranhamnafas"
}

quran_main_buttontxt = ["Qur'oni Karim tilovati (Hasanxon va Husaynxon qorilar)", "Qur'on bilan tanishuv",
                        "Mus'har istilohlari sharhi", "Iqro", "O'n kecha bilan qasam (1-bosqich)",
                        "O'n kecha bilan qasam (2-bosqich)", "O'n kecha bilan qasam (3-bosqich)",
                        "Qur'on tartili", "Qur'oni Karim tilovati (ta'lim uslubida)", "Qur'oni Karim (rasm/matn)",
                        "Qur'on ta'limiga oid suhbat va tavsiyalar", "Qur'on ila hamnafas"]

husary_dict = {'Fotiha': {'tartib_raqam': '001',
                          'audio': 'CQACAgIAAxkBAAECu8tiiOkEqU1zz3POoR086bOcQSWe3AACoSAAAtldSUgUL0vXDVEgWiQE',
                          'zip': 'BQACAgIAAxkBAAEC0mBiieQhfQqYCZFaqzVnWD8R5JLpCAACgBcAAiymUEi8w17W6t8TFCQE',
                          'oyat_soni': 7},
               'Baqara': {'tartib_raqam': '002',
                          'audio': 'CQACAgIAAxkBAAECvMBiiOoLrw6KZhjmCRcBPTZfgE92vwACpiAAAtldSUguJs1NwYrPyiQE',
                          'zip': 'BQACAgIAAxkBAAEC0xBiifDy6YYVAb0hrbhVGPJBQTq6tAACpRcAAiymUEjKQaIeGH_uoCQE',
                          'oyat_soni': 286},
               'Oli Imron': {'tartib_raqam': '003',
                             'audio': 'CQACAgIAAxkBAAECvQJiiOsFzJpOqhVvMdyn1Vp65pU7IwACqyAAAtldSUjYge2gNXHriSQE',
                             'zip': 'BQACAgIAAxkBAAEC0x5iifHi-pVIyAAB2iRZE5Y7RGlPWFsAAqgXAAIsplBIcm8Q1852GcAkBA',
                             'oyat_soni': 200},
               'Niso': {'tartib_raqam': '004',
                        'audio': 'CQACAgIAAxkBAAECvQxiiOuroFeHieNBeAPVQe_4k5qzbgACriAAAtldSUgi_5FlvHdP6iQE',
                        'zip': 'BQACAgIAAxkBAAEC0yBiifKDiyIIcveLzM0Um7i0cCGCegACqRcAAiymUEjGTMakrmDUAAEkBA',
                        'oyat_soni': 176},
               'Moida': {'tartib_raqam': '005',
                         'audio': 'CQACAgIAAxkBAAECvRRiiOw1LSeqQEbq8GzduLurJm7HnQACryAAAtldSUgdcKOcmlFnxiQE',
                         'zip': 'BQACAgIAAxkBAAEC0yJiifL8y0_sdmlKCL2kywmYcoxDxQACrBcAAiymUEj0XkKSFIYEAAEkBA',
                         'oyat_soni': 120},
               "An'om": {'tartib_raqam': '006',
                         'audio': 'CQACAgIAAxkBAAECvSJiiOzDdrnhgcCvpsxyR4aNVx5vNgACsCAAAtldSUibLro_G-6HmCQE',
                         'zip': 'BQACAgIAAxkBAAEC0yRiifN9P5D9a3AFhLxd9TAsJaGkvgACrxcAAiymUEgolhy3SSQXCyQE',
                         'oyat_soni': 165},
               "A'rof": {'tartib_raqam': '007',
                         'audio': 'CQACAgIAAxkBAAECvTliiO1NrUOrOjnNLt5PKndZf5G8CgACsiAAAtldSUhC-owKUg3D9CQE',
                         'zip': 'BQACAgIAAxkBAAEC0y1iifP9PSivt8SC7YygNhOa9WMisAACsxcAAiymUEg8-x8J32RW8CQE',
                         'oyat_soni': 206},
               'Anfol': {'tartib_raqam': '008',
                         'audio': 'CQACAgIAAxkBAAECvTtiiO3ClkhgQ2TiQCg-b-NlWUzYNAACtyAAAtldSUhPlrucYZ5ZFiQE',
                         'zip': 'BQACAgIAAxkBAAEC0zFiifQzvV3_H01qMRhmRor-G4GiqAACtBcAAiymUEjN5JiiO57uOiQE',
                         'oyat_soni': 75},
               'Tavba': {'tartib_raqam': '009',
                         'audio': 'CQACAgIAAxkBAAECvV1iiO53yHVzVh2TWhTu5t-7yeJDfgACvSAAAtldSUg4ITNhDWNa1CQE',
                         'zip': 'BQACAgIAAxkBAAEC0zNiifSivgu3fYXYPFZFn0m5JBn4dQACthcAAiymUEg85153jdWeWSQE',
                         'oyat_soni': 129},
               'Yunus': {'tartib_raqam': '010',
                         'audio': 'CQACAgIAAxkBAAECvWFiiO8UWuvBCzvBdRjE3ead2ES_8AACwiAAAtldSUhfnujYHruSJyQE',
                         'zip': 'BQACAgIAAxkBAAEC0zViifTtD06MZjRmaFdTIpYKnaftYwACuBcAAiymUEioRxUoz0tiayQE',
                         'oyat_soni': 109},
               'Hud': {'tartib_raqam': '011',
                       'audio': 'CQACAgIAAxkBAAECva9iiPOFNpIR0eCtwUFRJqLfJyaA-gAC2CAAAtldSUhMvp-wzKRoYiQE',
                       'zip': 'BQACAgIAAxkBAAEC00JiifaSZIcpNunssgrGAAE9z3t2DLUAAr4XAAIsplBIFsfBl6R_cLckBA',
                       'oyat_soni': 123},
               'Yusuf': {'tartib_raqam': '012',
                         'audio': 'CQACAgIAAxkBAAECvbRiiPPPig6XbFKVJD0vw8wqoS6NTwAC2iAAAtldSUgMLMvh4Cx3wCQE',
                         'zip': 'BQACAgIAAxkBAAEC00piifba48HZ70XQ6u3tGjy-BtcABL8XAAIsplBIw_LiwZuucJskBA',
                         'oyat_soni': 111},
               "Ra'd": {'tartib_raqam': '013',
                        'audio': 'CQACAgIAAxkBAAECvbxiiPP9hovGQksKfWrbxbMF42fXiQAC2yAAAtldSUinCxtBhneaMCQE',
                        'zip': 'BQACAgIAAxkBAAEC005iifcLT69eJwIDCKReYijczR5sFQACwBcAAiymUEg_oCbcC67KsCQE',
                        'oyat_soni': 43},
               'Ibrohim': {'tartib_raqam': '014',
                           'audio': 'CQACAgIAAxkBAAECvb5iiPQjPKjxNPkgYhJe_q6_aEAm5QAC3CAAAtldSUjYzu44IV5soSQE',
                           'zip': 'BQACAgIAAxkBAAEC011iifdLezq__udC2-Hg7TJ-ts58SAACwRcAAiymUEhVguLkQfpPgSQE',
                           'oyat_soni': 52},
               'Hijr': {'tartib_raqam': '015',
                        'audio': 'CQACAgIAAxkBAAECvcBiiPRUtLpBOls0B0nvOArudEEzPgAC3SAAAtldSUhZ9kLGiSZgiCQE',
                        'zip': 'BQACAgIAAxkBAAEC02liifdtgu04ld6h9R3uhG6Wjc5Z_QACwhcAAiymUEiorbAZg9XfBCQE',
                        'oyat_soni': 99},
               'Nahl': {'tartib_raqam': '016',
                        'audio': 'CQACAgIAAxkBAAECvctiiPSiAZ9wd_XaCBHzoLSnx2HOnwAC4CAAAtldSUgrntcaZoIDnCQE',
                        'zip': 'BQACAgIAAxkBAAEC03Fiife2FsH3chr6EuHVoHUqZ_-1WQACwxcAAiymUEjeX5SrUVkiJSQE',
                        'oyat_soni': 128},
               'Isro': {'tartib_raqam': '017',
                        'audio': 'CQACAgIAAxkBAAECvdNiiPTljMIUSxzkm9Ux91CigV_Y3wAC4SAAAtldSUiB_g6_ZivR8yQE',
                        'zip': 'BQACAgIAAxkBAAEC04liiff50SYLutL8LsRJRinqXGICNQACyhcAAiymUEifGWyzqVC4qiQE',
                        'oyat_soni': 111},
               'Kahf': {'tartib_raqam': '018',
                        'audio': 'CQACAgIAAxkBAAECvdliiPUnqpWAN14UBMYwZOw_gyptjAAC4iAAAtldSUgPi9ILJEnXYyQE',
                        'zip': 'BQACAgIAAxkBAAEC061iifg6pG_jXcruOG1-zbC0AAGmcnoAAucXAAIsplBIxvjKatNfvyAkBA',
                        'oyat_soni': 110},
               'Maryam': {'tartib_raqam': '019',
                          'audio': 'CQACAgIAAxkBAAECvdtiiPVRei5ZW1ygLmnD_0VCjsAN6wAC4yAAAtldSUigEv5qkZu3cSQE',
                          'zip': 'BQACAgIAAxkBAAEC069iifhkwiQjrxzY8QYuXxSmWJstcAAC6BcAAiymUEjZ5KDC05XI4SQE',
                          'oyat_soni': 98},
               'Toha': {'tartib_raqam': '020',
                        'audio': 'CQACAgIAAxkBAAECveNiiPWIDN_ObZnfEnNFJJLqlO5AHAAC5CAAAtldSUjDzF3Xx8XoICQE',
                        'zip': 'BQACAgIAAxkBAAEC07FiifibbbtKB_owhGhfrmnyo03O7AAC6RcAAiymUEhq08y8CmFKkSQE',
                        'oyat_soni': 135},
               'Anbiyo': {'tartib_raqam': '021',
                          'audio': 'CQACAgIAAxkBAAECvediiPW5Hm77iS5FvKnYCkoOFVMSlAAC5SAAAtldSUhJiPjVQlgjaCQE',
                          'zip': 'BQACAgIAAxkBAAEC07NiifjMLGG49GqgI1gq-A8j0TGlRAAC7BcAAiymUEis7TZROzwkJiQE',
                          'oyat_soni': 112},
               'Haj': {'tartib_raqam': '022',
                       'audio': 'CQACAgIAAxkBAAECvfViiPXvkmjsxxFzSTd0kG46Aesh3QAC5yAAAtldSUjjL56-zVdbfyQE',
                       'zip': 'BQACAgIAAxkBAAEC07ViifkC_ljvt_ImN6MmFM3Yrv-o1gAC7RcAAiymUEgUn2UliB3MeyQE',
                       'oyat_soni': 78},
               "Mu'minun": {'tartib_raqam': '023',
                            'audio': 'CQACAgIAAxkBAAECvfdiiPYdiZSkRnrubGzRAAGBUOrqSNoAAuogAALZXUlITJtcmFL9QIIkBA',
                            'zip': 'BQACAgIAAxkBAAEC07liifldfDN7twdrl8MTe18TUZ4f-wAC7xcAAiymUEgtZ9G1WUwU5SQE',
                            'oyat_soni': 118},
               'Nur': {'tartib_raqam': '024',
                       'audio': 'CQACAgIAAxkBAAECvfliiPZYNV5cUSCkv7v065Cmw6gupQAC7CAAAtldSUhbJNPgfkoOESQE',
                       'zip': 'BQACAgIAAxkBAAEC07tiifnMFk9IG3L8suZpSjKCbbLXEQAC8BcAAiymUEjaqlkxSxHJFSQE',
                       'oyat_soni': 64},
               'Furqon': {'tartib_raqam': '025',
                          'audio': 'CQACAgIAAxkBAAECvf1iiPaDMyVbq2gDV0YuDhdf8h_r1wAC7iAAAtldSUhg8I2uEwWDlCQE',
                          'zip': 'BQACAgIAAxkBAAEC071iifou8YfAmsmSSYha_Ju7fZFNGQAC8hcAAiymUEixAXXUtvwB-SQE',
                          'oyat_soni': 77},
               'Shuaro': {'tartib_raqam': '026',
                          'audio': 'CQACAgIAAxkBAAECvgFiiPbI33E_lpXI1GuJ6dBWbrq8KAAC8CAAAtldSUjmZqrjFiO23SQE',
                          'zip': 'BQACAgIAAxkBAAEC079iifpyVCikUVNwXcFdNB30LIaVPgAC8xcAAiymUEia9WaQOAyesCQE',
                          'oyat_soni': 227},
               'Naml': {'tartib_raqam': '027',
                        'audio': 'CQACAgIAAxkBAAECvgNiiPb9EoEoqnWGX5r9LycCWS3e9wAC8iAAAtldSUh3wG5o2FbMUiQE',
                        'zip': 'BQACAgIAAxkBAAEC08NiifrV0-UyOHJU8FAV9bs033UzYAAC9RcAAiymUEhlefIs33t-lyQE',
                        'oyat_soni': 93},
               'Qosos': {'tartib_raqam': '028',
                         'audio': 'CQACAgIAAxkBAAECvg1iiPc373HrGw9x8wIgQGFsvw2CXwAC9CAAAtldSUiwxOsaDFJpoCQE',
                         'zip': 'BQACAgIAAxkBAAEC08Viifschg_HvSU-Tsj971tbQRjpQQAC9xcAAiymUEgfizt-LYX6PyQE',
                         'oyat_soni': 88},
               'Ankabut': {'tartib_raqam': '029',
                           'audio': 'CQACAgIAAxkBAAECvhliiPdi6nwMyI_iYtHz0WLi0Of12AAC9yAAAtldSUixar23N0rRmiQE',
                           'zip': 'BQACAgIAAxkBAAEC08diiftGXw4-2DbVhR1lGNgqKC-lHwAC-BcAAiymUEg5mcSFIOvZ8yQE',
                           'oyat_soni': 69},
               'Rum': {'tartib_raqam': '030',
                       'audio': 'CQACAgIAAxkBAAECvhtiiPea5CUxdeDTYRI89LUQEnEGiwAC-SAAAtldSUiF8YTckxXgKCQE',
                       'zip': 'BQACAgIAAxkBAAEC08liift7vUv1tO6LblHYf7m9vjC3XAACOhQAAtLuUEiuEBIWkJJOVCQE',
                       'oyat_soni': 60},
               'Luqmon': {'tartib_raqam': '031',
                          'audio': 'CQACAgIAAxkBAAECviBiiPe_FnBaBO_vCh_-QAn3gUdnNQAC_iAAAtldSUjTZBU2ehZ0wyQE',
                          'zip': 'BQACAgIAAxkBAAEC08tiifuTE9f4mb_DsWMz9SVPcx6bywAC-hcAAiymUEjHELmJPjmwiCQE',
                          'oyat_soni': 34},
               'Sajda': {'tartib_raqam': '032',
                         'audio': 'CQACAgIAAxkBAAECvihiiPfYjt3QWXNj6_QqcdJeONJ3EwAC_yAAAtldSUh5EBAVFXXFcSQE',
                         'zip': 'BQACAgIAAxkBAAEC081iifukzH0TYOeFjff6VtV7dL9YnAAC_RcAAiymUEianiO6XYm1qCQE',
                         'oyat_soni': 30},
               'Ahzob': {'tartib_raqam': '033',
                         'audio': 'CQACAgIAAxkBAAECvlhiiPgN9sbQMFhE-6k9Flny9egGKgACAiEAAtldSUgLvQP_mlNP1SQE',
                         'zip': 'BQACAgIAAxkBAAEC09Jiifva1pmXrDsHgGZpnJ6k6DxmyAAC_hcAAiymUEjCxlMYx5sjtCQE',
                         'oyat_soni': 73},
               'Saba': {'tartib_raqam': '034',
                        'audio': 'CQACAgIAAxkBAAECvqdiiPhHqZSTwisHROdwniCkufD40QACBCEAAtldSUg-2mEdtYp0ESQE',
                        'zip': 'BQACAgIAAxkBAAEC09RiifwXidBCK0PfhpFQIovTvAwYFgADGAACLKZQSHDtXIyqZCUBJAQ',
                        'oyat_soni': 54},
               'Fotir': {'tartib_raqam': '035',
                         'audio': 'CQACAgIAAxkBAAECvrZiiPhyR3NhakKjg--CzeWGb1HG4QACBSEAAtldSUjwMwyBnop_SyQE',
                         'zip': 'BQACAgIAAxkBAAEC09hiifw_v1Sf-b0K_U_cQsDNgA6aNAACARgAAiymUEhjzD39uYMuayQE',
                         'oyat_soni': 45},
               'Yaasiyn': {'tartib_raqam': '036',
                           'audio': 'CQACAgIAAxkBAAECvrxiiPiXnPvXmw1ayUsCe4GdnRgWngACByEAAtldSUjWW0HjxCFXFiQE',
                           'zip': 'BQACAgIAAxkBAAEC09tiifxkYttKmp_snwnJr5_3MRXPHQACAhgAAiymUEgAAUydJ1-Yx0IkBA',
                           'oyat_soni': 83},
               'Soffaat': {'tartib_raqam': '037',
                           'audio': 'CQACAgIAAxkBAAECvsJiiPjJso24qbMw4Th5qb6DZuwuAgACCSEAAtldSUjzfWeY-LIxsSQE',
                           'zip': 'BQACAgIAAxkBAAEC091iifyMt-6ijvWIBmrxyTxegXAXMQACBBgAAiymUEiXyvKAZZHpayQE',
                           'oyat_soni': 182},
               'Sod': {'tartib_raqam': '038',
                       'audio': 'CQACAgIAAxkBAAECvsliiPjrrCrqoQXaxcD2xr107mWEZwACCiEAAtldSUjyiWdGtQ3zxyQE',
                       'zip': 'BQACAgIAAxkBAAEC099iifzDNTRXVnLvE_6JCPzEtC49IAACBxgAAiymUEgiw23gBILbbSQE',
                       'oyat_soni': 88},
               'Zumar': {'tartib_raqam': '039',
                         'audio': 'CQACAgIAAxkBAAECvthiiPkch8evNb2Qn3uEt9-357wYoQACDCEAAtldSUjVl1N6Lcb21yQE',
                         'zip': 'BQACAgIAAxkBAAEC0-Fiifz0aiW18_qWufe922iCAAHH-5AAAgkYAAIsplBIax7wZwR_LMQkBA',
                         'oyat_soni': 75},
               "G'ofir": {'tartib_raqam': '040',
                          'audio': 'CQACAgIAAxkBAAECvtpiiPlKF0nyT28RZRmaf3DXNdaG7AACDSEAAtldSUgCMxuHEqPq5yQE',
                          'zip': 'BQACAgIAAxkBAAEC0-Niif0iX55gGjBcdIceAAFQkNOm6XAAAgsYAAIsplBIAcWTYP99G44kBA',
                          'oyat_soni': 85},
               'Fussilat': {'tartib_raqam': '041',
                            'audio': 'CQACAgIAAxkBAAECvtxiiPl3OpCi0YTz-6-CsXKOUBjdEgACDiEAAtldSUiBh-c9WoPXhCQE',
                            'zip': 'BQACAgIAAxkBAAEC0_RiigABDqwW2V3ZwwtgDhyn6_wI4OAAAh8YAAIsplBIpngPRo7e8ickBA',
                            'oyat_soni': 54},
               'Shuuro': {'tartib_raqam': '042',
                          'audio': 'CQACAgIAAxkBAAECvuhiiPm0arfQyqFmB0Fg3QlNmCJZpgACDyEAAtldSUhMMOOoHwOOVSQE',
                          'zip': 'BQACAgIAAxkBAAEC0_ZiigABMgJZx9_9agaWIJIBrGbxvVYAAiEYAAIsplBIn5zTuUKlDDIkBA',
                          'oyat_soni': 53},
               'Zuxruf': {'tartib_raqam': '043',
                          'audio': 'CQACAgIAAxkBAAECvvRiiPnuNyZO1poy02FbnnXRemKbCAACECEAAtldSUhy7L65BDFItiQE',
                          'zip': 'BQACAgIAAxkBAAEC0_hiigABVUH_ClwJoIlzJD7UCBFiybIAAiIYAAIsplBIk-Aor7bXojgkBA',
                          'oyat_soni': 89},
               'Duxon': {'tartib_raqam': '044',
                         'audio': 'CQACAgIAAxkBAAECvvhiiPoE2BYPsEZkPYkwhh7U18AhbQACESEAAtldSUicMJvqhWnWWCQE',
                         'zip': 'BQACAgIAAxkBAAEC0_piigABfFEP7Lzh5rw2eiiAAnpr3q8AAiUYAAIsplBIFrQUsuZTtGMkBA',
                         'oyat_soni': 59},
               'Josiya': {'tartib_raqam': '045',
                          'audio': 'CQACAgIAAxkBAAECvwNiiPokxWvuc2XrKRAxp6C0hE2uhgACEyEAAtldSUiPOOrxy_9jJSQE',
                          'zip': 'BQACAgIAAxkBAAEC0_xiigABmN6pu5VrNwSHXSQxArEKaygAAicYAAIsplBIlCixgBz1MK8kBA',
                          'oyat_soni': 37},
               'Ahqof': {'tartib_raqam': '046',
                         'audio': 'CQACAgIAAxkBAAECvw9iiPpRrDj_5tGSPX6VN3wDq2mt-AACFCEAAtldSUiid8lp4lnW3CQE',
                         'zip': 'BQACAgIAAxkBAAEC1AFiigAByT3Znj7-SPlJI2HzAdkyGjAAAikYAAIsplBIvLFKeUmzokUkBA',
                         'oyat_soni': 35},
               'Muhammad': {'tartib_raqam': '047',
                            'audio': 'CQACAgIAAxkBAAECvxxiiPp3hNI85QO61HzqKmBH6o0SmwACFSEAAtldSUhtClZZ82BX2CQE',
                            'zip': 'BQACAgIAAxkBAAEC1ApiigEEIPEKAy22Q9LnIJfO3-kIJQACKhgAAiymUEgKN79_dM4B_iQE',
                            'oyat_soni': 38},
               'Fath': {'tartib_raqam': '048',
                        'audio': 'CQACAgIAAxkBAAECvyRiiPqVGB37lwG29CGv2mZhc-Or2QACFiEAAtldSUiABx11SkqiiSQE',
                        'zip': 'BQACAgIAAxkBAAEC1BliigFDZgbDQD-qJGTbpDG_DkkkogACLBgAAiymUEgtUQcnRjisRSQE',
                        'oyat_soni': 29},
               'Hujurot': {'tartib_raqam': '049',
                           'audio': 'CQACAgIAAxkBAAECvyhiiPqtpmSL_Smc6lLgln02kUCugQACFyEAAtldSUhpGMIxGsG6TiQE',
                           'zip': 'BQACAgIAAxkBAAEC1CZiigFds7dU8UFQj7uJdoZe8rviZgACLRgAAiymUEh607co27CnLiQE',
                           'oyat_soni': 18},
               'Qof': {'tartib_raqam': '050',
                       'audio': 'CQACAgIAAxkBAAECvy5iiPrIpiHB8Py7P-zFBNR5z-01mwACGCEAAtldSUh60bmcSgSd1CQE',
                       'zip': 'BQACAgIAAxkBAAEC1CxiigFtIJRfp_KJxa50Kj-63hWJPgACLhgAAiymUEjbrQy42AVe9iQE',
                       'oyat_soni': 45},
               'Zaariyaat': {'tartib_raqam': '051',
                             'audio': 'CQACAgIAAxkBAAECvzBiiPriVegXJIMnRFurVEuvmm7wXQACGSEAAtldSUjaxvli72R0OyQE',
                             'zip': 'BQACAgIAAxkBAAEC1DliigF_CgjfURFn2aG_vnNfq2zCXQACLxgAAiymUEj9fLmq_TkUgyQE',
                             'oyat_soni': 60},
               'Tur': {'tartib_raqam': '052',
                       'audio': 'CQACAgIAAxkBAAECvzJiiPr5TNV_dq9fDDi9Fs7L3Rq-fQACGiEAAtldSUijJgfSAYYr6SQE',
                       'zip': 'BQACAgIAAxkBAAEC1D1iigGNkDshKAr0FRymrecLCERRWQACMBgAAiymUEjmu6twIGBeFiQE',
                       'oyat_soni': 49},
               'Najm': {'tartib_raqam': '053',
                        'audio': 'CQACAgIAAxkBAAECvzRiiPsTj-4ahC08xK2IiNtwqNIffQACGyEAAtldSUijEsJTMSc4uiQE',
                        'zip': 'BQACAgIAAxkBAAEC1D9iigGmtVNQqAr3J1VsEUF4fzfBjwACMhgAAiymUEhYTrKN9wrNiiQE',
                        'oyat_soni': 62},
               'Qamar': {'tartib_raqam': '054',
                         'audio': 'CQACAgIAAxkBAAECvzhiiPsj4lMojbvnY-j_dViCctfCmAACHCEAAtldSUhY8KLdPNqRLSQE',
                         'zip': 'BQACAgIAAxkBAAEC1EFiigHNy9l_ZkgMGYn5WaULoDdC_QACNxgAAiymUEg4V114lSinDCQE',
                         'oyat_soni': 55},
               'Ar-Rohman': {'tartib_raqam': '055',
                             'audio': 'CQACAgIAAxkBAAECvz5iiPtDMiBOGmwGxbg-4YAf0NyglwACHSEAAtldSUhrbt8HYRgoZSQE',
                             'zip': 'BQACAgIAAxkBAAEC1ENiigHwgU2y1etwqwVhLLFF_wM64AACPBgAAiymUEhvtLyEusfSdiQE',
                             'oyat_soni': 78},
               "Voqi'a": {'tartib_raqam': '056',
                          'audio': 'CQACAgIAAxkBAAECv7JiiQEHVxKeToTmRwABtcvftd9DoG0AAkghAALZXUlIg6F-V-_g2jokBA',
                          'zip': 'BQACAgIAAxkBAAEC1EViigIaJCiq0pi6TR_XC8yw4_l_-AACPxgAAiymUEjIHb-JphJiQyQE',
                          'oyat_soni': 96},
               'Hadid': {'tartib_raqam': '057',
                         'audio': 'CQACAgIAAxkBAAECv7RiiQEca3vFxLbrpcxCZrJy-1U8UAACSSEAAtldSUh0f7ZbqHMcGyQE',
                         'zip': 'BQACAgIAAxkBAAEC1EdiigJVhph7mvFFvQy_NrDLyfr8nAACRBgAAiymUEj4aOziCGGhgyQE',
                         'oyat_soni': 29},
               'Mujodala': {'tartib_raqam': '058',
                            'audio': 'CQACAgIAAxkBAAECv7ZiiQEyTGOH2WYyLc2O0DaMiIcx-AACTSEAAtldSUhIFVEyOonpvCQE',
                            'zip': 'BQACAgIAAxkBAAEC1EliigJ2pV4FWvAVqUFa5zHRd3QJrgACRRgAAiymUEgvQYot_kK_XSQE',
                            'oyat_soni': 22},
               'Hashr': {'tartib_raqam': '059',
                         'audio': 'CQACAgIAAxkBAAECv7hiiQFGvPuk98MHXYxORuHNZzL0mgACUCEAAtldSUi7swNYOajfYSQE',
                         'zip': 'BQACAgIAAxkBAAEC1EtiigKZ2p3ubyjdPsY5ZFsE8d-_AQACRxgAAiymUEiJGjxMAAH1fxIkBA',
                         'oyat_soni': 24},
               'Mumtahana': {'tartib_raqam': '060',
                             'audio': 'CQACAgIAAxkBAAECv7piiQFY6NsyaHwuyOMuXEwnnb4yXgACUiEAAtldSUif1knCjODiVSQE',
                             'zip': 'BQACAgIAAxkBAAEC1E1iigKqIHCUe7vPRu6O0LH9AX640AACSRgAAiymUEhnt-QEaI6E0SQE',
                             'oyat_soni': 13},
               'Soff': {'tartib_raqam': '061',
                        'audio': 'CQACAgIAAxkBAAECv7xiiQFlDTa4YXGqupXTypaMelBtcQACVCEAAtldSUj-CCem1q6x0iQE',
                        'zip': 'BQACAgIAAxkBAAEC1E9iigK1BGlSPCk9TUvEl254cmeJ3QACSxgAAiymUEjT1WuQ8jYmaSQE',
                        'oyat_soni': 14},
               "Jumu'a": {'tartib_raqam': '062',
                          'audio': 'CQACAgIAAxkBAAECv75iiQFuEtGGR7xoAUANmVmW2_IMZQACVSEAAtldSUgiR1oas19eZCQE',
                          'zip': 'BQACAgIAAxkBAAEC1FFiigK8QWoqzzmrRYupQgWTAAH8lkEAAk0YAAIsplBIPTyG8Dzfc8EkBA',
                          'oyat_soni': 11},
               'Munofiqun': {'tartib_raqam': '063',
                             'audio': 'CQACAgIAAxkBAAECv8BiiQF7ev18oMv3Qds-sqWJzuJbKQACViEAAtldSUgzF34yHPslfiQE',
                             'zip': 'BQACAgIAAxkBAAEC1FNiigLFfv4FA9Wspx6yypYbsLZ1OwACThgAAiymUEhcGEaMeBBXYSQE',
                             'oyat_soni': 11},
               "Tag'obun": {'tartib_raqam': '064',
                            'audio': 'CQACAgIAAxkBAAECv8JiiQGL0IqAu-80cTaVODmN9ugK8gACWCEAAtldSUhdUrRwhUQYoSQE',
                            'zip': 'BQACAgIAAxkBAAEC1FViigLf88R1AofO0tipufXdukFf4QACUBgAAiymUEgwe41WPoutNyQE',
                            'oyat_soni': 18},
               'Taloq': {'tartib_raqam': '065',
                         'audio': 'CQACAgIAAxkBAAECv8RiiQGcsT-UiuaT5wgwXfHRc08n9gACXCEAAtldSUiK1USDobDbRyQE',
                         'zip': 'BQACAgIAAxkBAAEC1FdiigL1pCDGKTk8nxkLfKx4FVK2AwACURgAAiymUEiPAruqOJ12aCQE',
                         'oyat_soni': 12},
               'Tahrim': {'tartib_raqam': '066',
                          'audio': 'CQACAgIAAxkBAAECv8ZiiQGuDIoxpjFuoE64i_6sLScrBgACXSEAAtldSUg7srQF64DolSQE',
                          'zip': 'BQACAgIAAxkBAAEC1FliigMB7eAotgQ59I_RizGGO7O5DwACUxgAAiymUEgTeZGWOolRjCQE',
                          'oyat_soni': 12},
               'Mulk': {'tartib_raqam': '067',
                        'audio': 'CQACAgIAAxkBAAECv8liiQHBGo4ZssklrQ5FdvF7EMudDwACYCEAAtldSUhKU6m4yNuEfyQE',
                        'zip': 'BQACAgIAAxkBAAEC1FtiigMOTuvrgCT69BPFcgpWDvFVRgACVRgAAiymUEiYF3oggAZtXiQE',
                        'oyat_soni': 30},
               'Qalam': {'tartib_raqam': '068',
                         'audio': 'CQACAgIAAxkBAAECv8tiiQHbGeOBKGtp5QTTfBi5DXC-8gACYyEAAtldSUiLiyf4NYmtcCQE',
                         'zip': 'BQACAgIAAxkBAAEC1F1iigMc54o520q043h4sTMJePKlzwACVhgAAiymUEisaLJm7FgNcyQE',
                         'oyat_soni': 52},
               'Al-Haaqqoh': {'tartib_raqam': '069',
                              'audio': 'CQACAgIAAxkBAAECv81iiQHyNK8vyv_eVqYkDPPJDuF3VAACZSEAAtldSUgqIr8noD4GtiQE',
                              'zip': 'BQACAgIAAxkBAAEC1F9iigMopZLlR2KDJ3Q4J94IvV_CZgACWBgAAiymUEgaauzZi-JTpCQE',
                              'oyat_soni': 52},
               "Ma'orij": {'tartib_raqam': '070',
                           'audio': 'CQACAgIAAxkBAAECv89iiQICfuIxvAg2ZsyB7tjU40EuogACZyEAAtldSUhJNUl-9gcS0SQE',
                           'zip': 'BQACAgIAAxkBAAEC1GFiigMyNybpnoGqCk2S_DVO0JTufgACWhgAAiymUEiTz5i_2rLnsSQE',
                           'oyat_soni': 44},
               'Nuh': {'tartib_raqam': '071',
                       'audio': 'CQACAgIAAxkBAAECv9FiiQIPUqCMJFPmMsDnPmfpZaePJwACaSEAAtldSUi1vejXfNcn3iQE',
                       'zip': 'BQACAgIAAxkBAAEC1GNiigNCMJAlrm74oSRDGSMY2t3EpwACWxgAAiymUEjtAAHs5OgBEcMkBA',
                       'oyat_soni': 28},
               'Jin': {'tartib_raqam': '072',
                       'audio': 'CQACAgIAAxkBAAECv9ViiQInierI5kLHlZ7bsMsltDzGiAACayEAAtldSUhjO4QR1Dvd4SQE',
                       'zip': 'BQACAgIAAxkBAAEC1GViigNNKP0OfLR5I0FSDuNT7HCYMgACXRgAAiymUEgglIiP01dABCQE',
                       'oyat_soni': 28},
               'Muzzammil': {'tartib_raqam': '073',
                             'audio': 'CQACAgIAAxkBAAECv9diiQI3tdkRbdPoCEUBjo2D1XJgsgACbiEAAtldSUg230eePz2BWSQE',
                             'zip': 'BQACAgIAAxkBAAEC1GdiigNkBAv9NAw0KyT1hHiy-TbTuAACYBgAAiymUEgNQf-CFyjroSQE',
                             'oyat_soni': 20},
               'Muddassir': {'tartib_raqam': '074',
                             'audio': 'CQACAgIAAxkBAAECv-JiiQJNI6UVuXzP0UQwtTybNUZECwACcCEAAtldSUjwyDnXKcpTZSQE',
                             'zip': 'BQACAgIAAxkBAAEC1GliigN1jx0sAT5Ta_wfXyEec6p4YwACYxgAAiymUEjw_-zarKZucCQE',
                             'oyat_soni': 56},
               'Qiyaama': {'tartib_raqam': '075',
                           'audio': 'CQACAgIAAxkBAAECv-ZiiQJYcKC5WrdJl407XmzWZS9-ogACciEAAtldSUitECT6UPFHxCQE',
                           'zip': 'BQACAgIAAxkBAAEC1GtiigOJnyyiNvQlupYzIkLDzI36cAACZxgAAiymUEirmqOZI_nHUSQE',
                           'oyat_soni': 40},
               'Inson': {'tartib_raqam': '076',
                         'audio': 'CQACAgIAAxkBAAECv_BiiQJrnwdVE6DHoxzMHLXHJSlmEQACcyEAAtldSUidhxCVwBEHbCQE',
                         'zip': 'BQACAgIAAxkBAAEC1G1iigOl_jMCDzTfZmy1qdTGeUpNSAACbBgAAiymUEgiVNSZxfOkOiQE',
                         'oyat_soni': 31},
               'Mursalaat': {'tartib_raqam': '077',
                             'audio': 'CQACAgIAAxkBAAECv_JiiQJ_07KMsSYktrfnzqn5XjVNwgACdCEAAtldSUiOSVYNZaWC7yQE',
                             'zip': 'BQACAgIAAxkBAAEC1G9iigO4oyfXEQ2dKyBWDZX8iSahVgACbxgAAiymUEh9G4rVeUfIqyQE',
                             'oyat_soni': 50},
               "Naba'": {'tartib_raqam': '078',
                         'audio': 'CQACAgIAAxkBAAECu1JiiOgBkFho9cfn1Qm3UPM2rR1-7gACdSAAAtldSUjHU-MPeybMtyQE',
                         'zip': 'BQACAgIAAxkBAAEC1HFiigPGFlgxYXUWRqpj1kDORCupqAACcBgAAiymUEgf5oYvdcQiMiQE',
                         'oyat_soni': 40},
               "Nazi'aat": {'tartib_raqam': '079',
                            'audio': 'CQACAgIAAxkBAAECu1RiiOgRhcnCS4oYt-s9EJmzuE1pEQACdyAAAtldSUhZeDU85OHdwCQE',
                            'zip': 'BQACAgIAAxkBAAEC1HdiigPdHRZ80JSPPmpcN8yzrr1n9QACchgAAiymUEgB2BbW3fRl0yQE',
                            'oyat_soni': 46},
               'Abasa': {'tartib_raqam': '080',
                         'audio': 'CQACAgIAAxkBAAECu1hiiOhDYP1DPlD0c2hgv9-UJRMjbAACeiAAAtldSUhTWw6JdIMAAXIkBA',
                         'zip': 'BQACAgIAAxkBAAEC1HpiigPwhLGyzwABiM1jfz8ZuPvXwqkAAnQYAAIsplBIAtSiH-1WawckBA',
                         'oyat_soni': 42},
               'Takvir': {'tartib_raqam': '081',
                          'audio': 'CQACAgIAAxkBAAECu1piiOhIYnW-uvqvUcs3b6H6yCGi6AACeyAAAtldSUj-bKOtj1sGqyQE',
                          'zip': 'BQACAgIAAxkBAAEC1HxiigP98s9dHcxxEb8pd_OLvBGZCAACdhgAAiymUEg1URThkcM_YiQE',
                          'oyat_soni': 29},
               'Infitor': {'tartib_raqam': '082',
                           'audio': 'CQACAgIAAxkBAAECu1xiiOhPwLchEjltgLMukW1haS2i6QACfCAAAtldSUi6QW6AKpjnZyQE',
                           'zip': 'BQACAgIAAxkBAAEC1H5iigQHNqqJkMCfcKKVzkl1zJv0tgACdxgAAiymUEj1K3qaEAZqNCQE',
                           'oyat_soni': 19},
               'Mutoffifun': {'tartib_raqam': '083',
                              'audio': 'CQACAgIAAxkBAAECu15iiOhYaCCaxEKoBRdyx1Mjo-UgHwACfSAAAtldSUj1IVFo7mt10iQE',
                              'zip': 'BQACAgIAAxkBAAEC1IBiigQc0PAkmyQHclhnw7AhioF_hQACeRgAAiymUEi53tuQ7Wg1UCQE',
                              'oyat_soni': 36},
               'Inshiqoq': {'tartib_raqam': '084',
                            'audio': 'CQACAgIAAxkBAAECu2JiiOhd65zJHfTNySY5ZigZw-1PUAACfyAAAtldSUhqg71bQ0PGMSQE',
                            'zip': 'BQACAgIAAxkBAAEC1htiihbb74FtsyyFV9UYTgRzfMWypQACFxkAAiymUEjeagiJa-_NhiQE',
                            'oyat_soni': 25},
               'Buruj': {'tartib_raqam': '085',
                         'audio': 'CQACAgIAAxkBAAECu2ZiiOhk4iMwzkPjNkQS5Lo-Of8iYgACgCAAAtldSUjZ-24BN-Kk8iQE',
                         'zip': 'BQACAgIAAxkBAAEC1INiigQwkOgsWOnIWp2nToaIhnAKpgACexgAAiymUEjWKElAmUX5PiQE',
                         'oyat_soni': 22},
               'Toriq': {'tartib_raqam': '086',
                         'audio': 'CQACAgIAAxkBAAECu2piiOhol_ZYcF_4oTTRLdbtW9xwnAACgSAAAtldSUgOUd6DOVfRzyQE',
                         'zip': 'BQACAgIAAxkBAAEC1IZiigQ4U_E2P1mQp8Wm4PbiRWz_ZgACfBgAAiymUEiKkdIDavr3wiQE',
                         'oyat_soni': 17},
               "A'laa": {'tartib_raqam': '087',
                         'audio': 'CQACAgIAAxkBAAECu3BiiOhtJyxV_r8LAuGZ3rM8sv-7_gACgiAAAtldSUj2pL_VIqz31iQE',
                         'zip': 'BQACAgIAAxkBAAEC1IhiigRC_oJFXmJOiLBZInJOmMQCTQACfhgAAiymUEhe7J5KXlIOriQE',
                         'oyat_soni': 19},
               "G'oshiya": {'tartib_raqam': '088',
                            'audio': 'CQACAgIAAxkBAAECu3tiiOh4ESna4wYaHMLwtT0eQ5psKQACgyAAAtldSUjfmB9n3jx8EiQE',
                            'zip': 'BQACAgIAAxkBAAEC1IpiigRMubQL7eFDZqcR5mkYayDcZgACfxgAAiymUEgzIJZvLpEVLiQE',
                            'oyat_soni': 26},
               'Fajr': {'tartib_raqam': '089',
                        'audio': 'CQACAgIAAxkBAAECu4ZiiOiB8Gsl3sTPsMqkDM5DbGLl8AAChCAAAtldSUg9M1DjfKxrziQE',
                        'zip': 'BQACAgIAAxkBAAEC1IxiigRdGM6Fxc8M7jz6hqbuN4FxwAACghgAAiymUEiOk4dmCvkfOyQE',
                        'oyat_soni': 30},
               'Balad': {'tartib_raqam': '090',
                         'audio': 'CQACAgIAAxkBAAECu4piiOiGJSS-yS_T_N_geZeaL53Y9wAChSAAAtldSUjkufvUKRAEuiQE',
                         'zip': 'BQACAgIAAxkBAAEC1I1iigRnXu6kTHFir8YGo3gR9DzHVQACgxgAAiymUEgvFDeFgxEY8CQE',
                         'oyat_soni': 20},
               'Shams': {'tartib_raqam': '091',
                         'audio': 'CQACAgIAAxkBAAECu45iiOiLRsDmHvLpphMZOO489dH4ygAChyAAAtldSUjigIYtWItRNiQE',
                         'zip': 'BQACAgIAAxkBAAEC18Viihmc30rytmeTa4Tq6yZsd3HikAACJRkAAiymUEi_clxCgD9wwiQE',
                         'oyat_soni': 15},
               'Layl': {'tartib_raqam': '092',
                        'audio': 'CQACAgIAAxkBAAECu5BiiOiS0_92kR8MWiozLK2qyRn_1QACiCAAAtldSUg6ZvLMUpfeUiQE',
                        'zip': 'BQACAgIAAxkBAAEC1JFiigR0oI6E0DyqjzDSgedYUqQKYQAChhgAAiymUEhE94R-YCU-QyQE',
                        'oyat_soni': 21},
               'Zuho': {'tartib_raqam': '093',
                        'audio': 'CQACAgIAAxkBAAECu5JiiOiYuWc0XHsDMd2s5GX-vwPiXwACiSAAAtldSUjQhJG1y9_aeSQE',
                        'zip': 'BQACAgIAAxkBAAEC2ApiihrWGNzfC8rdCcXBy2MiLZKCAQACMxkAAiymUEjEzNnSUBJp6CQE',
                        'oyat_soni': 11},
               'Sharh': {'tartib_raqam': '094',
                         'audio': 'CQACAgIAAxkBAAECu5ZiiOiaCvqZCyvBnTJP24cdVkSb8AACiiAAAtldSUjOpt6q_UO8vyQE',
                         'zip': 'BQACAgIAAxkBAAEC1JViigR9c5C0csvkz9pqn7QKmTqfTQACiRgAAiymUEgvswoqsJdC6iQE',
                         'oyat_soni': 8},
               'Tiyn': {'tartib_raqam': '095',
                        'audio': 'CQACAgIAAxkBAAECu5hiiOif3vIOCRp9Vx5HMkuDnOypGAACjCAAAtldSUgBV--Z-OZ7NyQE',
                        'zip': 'BQACAgIAAxkBAAEC19FiihncOHPJ19VTUf79R0dEumBleAACJxkAAiymUEgGFgpxecovfyQE',
                        'oyat_soni': 8},
               'Alaq': {'tartib_raqam': '096',
                        'audio': 'CQACAgIAAxkBAAECu5piiOim63ag1yahyxHX-xqZTInPMgACjSAAAtldSUghOAl-WQzkxyQE',
                        'zip': 'BQACAgIAAxkBAAEC1JhiigSJrJ463jrc4-P7icITzPzeiAACixgAAiymUEhoq1_aq9IDJSQE',
                        'oyat_soni': 19},
               'Qadr': {'tartib_raqam': '097',
                        'audio': 'CQACAgIAAxkBAAECu55iiOioBXByTKfVn7uEVdoQAAEWEusAAo4gAALZXUlIaAgwD1_yXVIkBA',
                        'zip': 'BQACAgIAAxkBAAEC2C9iihsxt09UQSc1bAwjL8zIny1sUQACjBgAAiymUEjvZ0js_82Y6CQE',
                        'oyat_soni': 5},
               'Bayyina': {'tartib_raqam': '098',
                           'audio': 'CQACAgIAAxkBAAECu6FiiOitRp7zuoEuvfA6f7S-DQYmLwACjyAAAtldSUi2_fHLny9SRSQE',
                           'zip': 'BQACAgIAAxkBAAEC1JxiigSX5HFCoy4nE3SuEo8BK5JEMAACjhgAAiymUEhUy5h57LhZdyQE',
                           'oyat_soni': 8},
               'Zalzala': {'tartib_raqam': '099',
                           'audio': 'CQACAgIAAxkBAAECu6NiiOixBWtx69-LO53N27whRjtpdAACkCAAAtldSUj9OVwHHNNeaSQE',
                           'zip': 'BQACAgIAAxkBAAEC2DdiihtRh6BzfLLdrxsBy3wf0TVQigACjxgAAiymUEhzQlmL1nJ0ASQE',
                           'oyat_soni': 8},
               'Adiyat': {'tartib_raqam': '100',
                          'audio': 'CQACAgIAAxkBAAECu6ZiiOi1J3jBx32pMPkFoak9Hg2ExQACkSAAAtldSUhMj0GBqP8bIiQE',
                          'zip': 'BQACAgIAAxkBAAEC19ViihoarRM_GsO-pt6J64BCYbonXgACLhkAAiymUEirsQKKz3Bj-yQE',
                          'oyat_soni': 11},
               "Qori'a": {'tartib_raqam': '101',
                          'audio': 'CQACAgIAAxkBAAECu6hiiOi4wLA8-Ybij6UerF-1Plwe_QACkiAAAtldSUh5MECIP1y_nyQE',
                          'zip': 'BQACAgIAAxkBAAEC2FViihujYy_zgRNOvv3IT3LEfQJzsQACkRgAAiymUEjbmwgg17aRqiQE',
                          'oyat_soni': 11},
               'Takaasur': {'tartib_raqam': '102',
                            'audio': 'CQACAgIAAxkBAAECu6piiOi6wPVWvNwz1LnxwUuuCvZfxgACkyAAAtldSUiB6yPiYAdIPiQE',
                            'zip': 'BQACAgIAAxkBAAEC2Ftiihu_UnHb61AGT8owziD33GvO7wACPBkAAiymUEhGuSv6NsdsUyQE',
                            'oyat_soni': 8},
               'Asr': {'tartib_raqam': '103',
                       'audio': 'CQACAgIAAxkBAAECu6xiiOi8ON2BaB0MpoyJ06l8a3jVzQAClCAAAtldSUjE8HKeP93nLCQE',
                       'zip': 'BQACAgIAAxkBAAEC2GNiihvIgJpCXQb9_PPu3TNc5foWrQACPRkAAiymUEjXH0mcSui7dSQE',
                       'oyat_soni': 3},
               'Humaza': {'tartib_raqam': '104',
                          'audio': 'CQACAgIAAxkBAAECu65iiOi__fCb8qbB-qqb0lrAnRyQewAClSAAAtldSUi9_JoFHon_fSQE',
                          'zip': 'BQACAgIAAxkBAAEC2GViihvNVhtzRvTDuqkxovmET64m1gACPhkAAiymUEg9ma_5-YguPSQE',
                          'oyat_soni': 9},
               'Fil': {'tartib_raqam': '105',
                       'audio': 'CQACAgIAAxkBAAECu7BiiOjDxYSYN6dEj4RLFdjuYL4VcgACliAAAtldSUjG4_N5F7RFtyQE',
                       'zip': 'BQACAgIAAxkBAAEC2GliihvSt_P6y-BCTBxx5NGHSYEG2gACPxkAAiymUEhMZ5Qu3iJZXyQE',
                       'oyat_soni': 5},
               'Quraysh': {'tartib_raqam': '106',
                           'audio': 'CQACAgIAAxkBAAECu7JiiOjGJVB7-0u2JrtT8R88js46fwAClyAAAtldSUg4UjNfCuNM0yQE',
                           'zip': 'BQACAgIAAxkBAAEC2G9iihvWM34iwRhBJ1afjim6JV1PIAACQBkAAiymUEh2slVI4Euy9CQE',
                           'oyat_soni': 4},
               "Maa'uun": {'tartib_raqam': '107',
                           'audio': 'CQACAgIAAxkBAAECu7RiiOjJklOJOFlPZnhSHrf3KUEXkgACmSAAAtldSUipYUivWH8uxCQE',
                           'zip': 'BQACAgIAAxkBAAEC2HFiihvaiaTukjJcWC-rfqhoRFnwHgACQRkAAiymUEiipSCNkWRSXCQE',
                           'oyat_soni': 7},
               'Kavsar': {'tartib_raqam': '108',
                          'audio': 'CQACAgIAAxkBAAECu7ZiiOjL92C3Q2JtUnr5YK6ZkTR-1gACmiAAAtldSUikHuqMVYzkYCQE',
                          'zip': 'BQACAgIAAxkBAAEC2HNiihveiNzLVNAGZmu3zkJjLU9y1QACQhkAAiymUEj65nR-tima-yQE',
                          'oyat_soni': 3},
               'Kaafirun': {'tartib_raqam': '109',
                            'audio': 'CQACAgIAAxkBAAECu7hiiOjQL7v_Wk71BTqF6vuKk4O4uAACmyAAAtldSUibGRQ0IH_psSQE',
                            'zip': 'BQACAgIAAxkBAAEC2HViihvkU3Ns3EUy97DuS4iyim3XYwACQxkAAiymUEhhq6WhCsPumCQE',
                            'oyat_soni': 6},
               'Nasr': {'tartib_raqam': '110',
                        'audio': 'CQACAgIAAxkBAAECu7piiOjTs97XMRf0569XHjXTYKymUQACnCAAAtldSUjniRCJ_cSQsCQE',
                        'zip': 'BQACAgIAAxkBAAEC2HdiihvopIffdayzG9cBFfvM3MO7BwACRBkAAiymUEgOHBe8QdfihSQE',
                        'oyat_soni': 3},
               'Masad': {'tartib_raqam': '111',
                         'audio': 'CQACAgIAAxkBAAECu7xiiOjW6d9GuXLsAhnMYlf2aS9fQgACnSAAAtldSUjyc8KgEKi6ESQE',
                         'zip': 'BQACAgIAAxkBAAEC2HliihvsrOGan3JP_8lxJt5k2zXvIQACRRkAAiymUEh1Q0PTmxNlcyQE',
                         'oyat_soni': 5},
               'Ixlos': {'tartib_raqam': '112',
                         'audio': 'CQACAgIAAxkBAAECu75iiOjYq2y9_7FMkN5bfnkl1wVimwACniAAAtldSUj3oo4LFxWRyCQE',
                         'zip': 'BQACAgIAAxkBAAEC2HtiihvvLtsBnT5R8gjAIOD6Q6EjHAACRhkAAiymUEj4DaNezqDMkSQE',
                         'oyat_soni': 4},
               'Falaq': {'tartib_raqam': '113',
                         'audio': 'CQACAgIAAxkBAAECu8BiiOjb7JpB4gHURxrwZjKKcZoLCQACnyAAAtldSUhkP5vdHO_GgCQE',
                         'zip': 'BQACAgIAAxkBAAEC2H1iihvyM9DsNgABWVOl-lwZwM--0eUAAkcZAAIsplBIC2gfJSXuSTwkBA',
                         'oyat_soni': 5},
               'Naas': {'tartib_raqam': '114',
                        'audio': 'CQACAgIAAxkBAAECu8JiiOjfokqSRQABy5EvdOjm1npgrbkAAqAgAALZXUlItrnrYheVlXckBA',
                        'zip': 'BQACAgIAAxkBAAEC2H9iihv2-t3KMOxiE6adZDWDXCMJiAACSBkAAiymUEile3PVCWVrkiQE',
                        'oyat_soni': 6}}
