# Generated by Django 5.1b1 on 2024-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranEDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=3, verbose_name='Tartib raqam')),
                ('sura_name', models.CharField(max_length=60, verbose_name='Sura nomi')),
                ('total_verses', models.IntegerField(verbose_name='Oyatlar soni')),
                ('zip', models.CharField(blank=True, max_length=200, null=True, verbose_name='ZIP ID')),
                ('audiomuqriy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Muqriy Audio ID')),
                ('audiohusary', models.CharField(blank=True, max_length=200, null=True, verbose_name='Husary Audio ID')),
                ('photo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Photo ID')),
                ('photo_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': "Qur'oni Karim (EDU ONE)",
                'verbose_name_plural': "Qur'oni Karim (EDU ONE)",
            },
        ),
    ]
