# Generated by Django 5.1 on 2024-08-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranedu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranedu',
            name='photo_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Photo link'),
        ),
    ]
